trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Pipeline started"
  displayName: 'Start message'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: chmod +x ./gradlew
  displayName: 'Give permission'

- script: ./gradlew assembleDebug
  displayName: 'Build APK'
